version: '3'
services:

  backend:
    build:
      context: .

    ports:
      - 5000:5000

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: DevOps
      MYSQL_PASSWORD: test@123
      MYSQL_DB: two_tier_app_database

    depends_on:
      - mysql

  mysql:
    image: mysql:5.7

    environment:
      MYSQL_ROOT_PASSWORD: test@123
      MYSQL_USER: DevOps
      MYSQL_PASSWORD: test@123
      MYSQL_DATABASE: two_tier_app_database

    volumes:
      - my-datavolume:/var/lib/mysql

volumes:
  my-datavolume:
